# OpenGraph / Twitter metadata
title: body
small_title: body
smallest_title: body
description: body
name: body

report_url: "https://www.dhs.gov/cyber"

# GA and GitHub data

repo: https://github.com/dhs-ncats/body

uswds_path: assets/vendor/uswds

exclude:
- CONTRIBUTING.md
- _config.yml
- .travis.yml
- .gitignore
- Gemfile
- Gemfile.lock
- LICENSE.md
- README.md
- vendor
- gulpfile.js
- manifest.yml
- package.json
- Staticfile
- Staticfile.auth
- node_modules
- .nvmrc
- .sass-cache
- todo.txt
- assets/sass


defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

collections:
  pages:
    output: true
    #permalink: /:path/
